### PR TITLE
Auto-Guess of Subtitle Label when loading Local Files via Regex in application.yml

### PR DESCRIPTION
**Pull request by Norwelian**
The title is self explanatory.
I've put the regex used for the subtitle label with the regexes of movies and tv shows in the application.yml, then it gets loaded when needed.
I've tested it for a few minutes now, and it seems to work just fine!
Good day!

### CODE REVIEW

**Comment by Norwelian** [comment]
The only thing that could be missing is a setting or something that allows you to turn this off, but I'm afraid I don't know how to add a new global setting (like the click-to-pause setting, for example).

**Comment by dularion** [comment]
This has been open for ages, sorry! to give you a hint on your second question: check out `settingsService.getValueForName('user_activity_rotation')`where `user_activity_rotation` is a name of a setting-instance.

**Comment by dularion** [comment]
I personally would like to add this feature, but disabled by default maybe? and then people can enable this if they wish to do so

**Comment by dularion** [comment]
Super cool, thanks for the contribution!

**Pull request merged**
